SET foreign_key_checks = 0;
DROP TABLE IF EXISTS `#__bookpro_country`;
DROP TABLE IF EXISTS `#__bookpro_agent`;
DROP TABLE IF EXISTS `#__bookpro_dest`;
DROP TABLE IF EXISTS `#__bookpro_passenger`;
DROP TABLE IF EXISTS `#__bookpro_flightratelog`;
DROP TABLE IF EXISTS `#__bookpro_flightrate`;
DROP TABLE IF EXISTS `#__bookpro_flight`;
DROP TABLE IF EXISTS `#__bookpro_orders`;
DROP TABLE IF EXISTS `#__bookpro_customer`;
DROP TABLE IF EXISTS `#__bookpro_cgroup`;
DROP TABLE IF EXISTS `#__bookpro_airline`;
DROP TABLE IF EXISTS `#__bookpro_category`;
DROP TABLE IF EXISTS `#__bookpro_application`;
DROP TABLE IF EXISTS `#__bookpro_state`;
DROP TABLE IF EXISTS `#__bookpro_aircraft`;
DROP TABLE IF EXISTS `#__bookpro_coupon`;
DROP TABLE IF EXISTS `#__bookpro_addon`;
DROP TABLE IF EXISTS `#__bookpro_orders_addon`;
DROP TABLE IF EXISTS `#__bookpro_aircraft`;
SET foreign_key_checks = 1;